# Predicción de Rendimiento Académico Estudiantil
### Clasificación con Regresión Logística, SVM y MLP
---
|                |   |
:----------------|---|
| **Nombre**     |  Jorge Oviedo Magaña, Louis Leone Blancas Moreyda, Emilio Navarro Cabrales|
| **Fecha**      | 06/04/2026 |
| **Expedientes** |  757048,  | 


## 1. Objetivos

### 1.1 Objetivo General
Desarrollar y comparar modelos de clasificación supervisada para predecir 
el rendimiento académico de estudiantes, identificando los factores con 
mayor influencia en la calificación final obtenida.

### 1.2 Objetivos Específicos
- Analizar y preprocesar el dataset de rendimiento estudiantil, 
  identificando las transformaciones necesarias para su uso en modelos de clasificación.
- Implementar tres modelos de clasificación (Regresión Logística, SVM con kernel RBF 
  y MLP), cada uno con optimización de hiperparámetros mediante procesos gaussianos.
- Evaluar y comparar el desempeño de los modelos mediante métricas de clasificación 
  aplicadas sobre k-folds cross-validation, reportando media y desviación estándar.
- Determinar qué modelo ofrece el mejor balance entre rendimiento predictivo 
  y costo computacional para este problema.

## 2. Marco Teórico

### 2.1 Regresión Logística
La regresión logística es un modelo de clasificación que estima la probabilidad 
de pertenencia a una clase mediante la función sigmoide. A pesar de su nombre, 
es un algoritmo de clasificación que modela la relación entre las variables 
independientes y una variable dependiente categórica.

Para problemas multiclase como el presente (clases A, B, C, D, F), se extiende 
mediante la estrategia One-vs-Rest (OvR), entrenando un clasificador binario 
por cada clase. La función de costo es la entropía cruzada, minimizada mediante 
descenso de gradiente.

La regularización controla el sobreajuste penalizando coeficientes grandes:
- **L1 (Lasso):** penalización con norma ‖w‖₁, produce modelos dispersos con 
  selección implícita de variables.
- **L2 (Ridge):** penalización con norma ‖w‖₂², distribuye el peso entre 
  variables correlacionadas.
- El hiperparámetro **C** controla la intensidad de la regularización; 
  un C pequeño implica mayor regularización.

### 2.2 Máquinas de Vectores de Soporte (SVM)
Las SVM buscan el hiperplano de máximo margen que separa las clases en el 
espacio de características. Los puntos más cercanos al hiperplano se denominan 
vectores de soporte y son los únicos que determinan la frontera de decisión.

Para datos no linealmente separables se introduce la variable de holgura ξᵢ 
(formulación soft-margin), controlada por el hiperparámetro **C**: valores altos 
penalizan fuertemente los errores de clasificación, valores bajos permiten 
mayor margen a costa de más errores de entrenamiento.

Para clasificación multiclase se utiliza la estrategia One-vs-Rest (OvR) 
o One-vs-One (OvO).

### 2.3 Redes Neuronales — Multi-layer Perceptron (MLP)
El MLP es una red neuronal feedforward compuesta por una capa de entrada, 
una o más capas ocultas y una capa de salida. Cada neurona aplica una 
transformación afín seguida de una función de activación no lineal (ReLU, 
tanh, sigmoide).

El entrenamiento se realiza mediante backpropagation y descenso de gradiente 
estocástico o variantes adaptativas como Adam. Los hiperparámetros principales 
incluyen el número de capas, neuronas por capa, función de activación, tasa de 
aprendizaje y regularización L2 (alpha). Para clasificación multiclase la capa 
de salida utiliza softmax, produciendo una distribución de probabilidad sobre 
las clases.

### 2.4 Kernels
Un kernel es una función K(xᵢ, xⱼ) que calcula el producto punto entre dos 
vectores en un espacio de características de alta dimensión sin necesidad de 
transformarlos explícitamente — conocido como el truco del kernel. Esto permite 
que modelos lineales como SVM aprendan fronteras de decisión no lineales.

El kernel RBF (Radial Basis Function) es el más utilizado en la práctica:

$$K(x_i, x_j) = \exp(-\gamma \|x_i - x_j\|^2)$$

El parámetro **γ** controla el radio de influencia de cada muestra: valores 
altos producen fronteras muy locales (riesgo de sobreajuste), valores bajos 
generan fronteras más suaves (riesgo de subajuste).

### 2.5 Métricas para Clasificación
Para un problema multiclase con posible desbalance de clases se consideran:

- **Accuracy:** proporción de predicciones correctas sobre el total. Puede ser 
  engañosa con clases desbalanceadas.
- **Precisión:** de los ejemplos predichos como clase C, cuántos realmente lo son.
- **Recall:** de los ejemplos que realmente son clase C, cuántos fueron 
  correctamente identificados.
- **F1-score macro:** media armónica de precisión y recall, promediada con igual 
  peso por clase. Penaliza el mal desempeño en clases minoritarias.
- **AUC-ROC macro:** área bajo la curva ROC promediada en esquema One-vs-Rest. 
  Mide la capacidad discriminativa del modelo independientemente del umbral.

La métrica principal de este proyecto es el **F1-score macro**.

### 2.6 Hiperparámetros
Los hiperparámetros son parámetros del modelo que no se aprenden durante el 
entrenamiento sino que se fijan antes de él. Su correcta selección es determinante 
para el desempeño del modelo.

| Modelo | Hiperparámetros clave |
|---|---|
| Regresión Logística | C, penalty (L1/L2), solver |
| SVM RBF | C, gamma |
| MLP | hidden_layer_sizes, learning_rate_init, alpha |

La búsqueda se realiza mediante 5-folds cross-validation para asegurar que 
la estimación del desempeño sea robusta y no dependa de una partición específica.

### 2.7 Optimización Bayesiana
La optimización bayesiana es un método de búsqueda de hiperparámetros más 
eficiente que Grid Search o Random Search. Construye un modelo probabilístico 
sustituto (proceso gaussiano) del desempeño del modelo en función de los 
hiperparámetros, y utiliza una función de adquisición (Expected Improvement) 
para decidir qué configuración evaluar a continuación.

Esto permite encontrar buenos hiperparámetros con menos evaluaciones, lo cual 
es especialmente valioso cuando el entrenamiento es costoso. En este proyecto 
se implementa mediante `BayesSearchCV` de la librería `scikit-optimize`.

### 2.8 Rendimiento Académico Estudiantil
El rendimiento académico es un fenómeno multidimensional influenciado por 
factores cognitivos, conductuales y socioeconómicos. Estudios en el área de 
educational data mining han identificado que variables como las horas de estudio, 
la asistencia y el acceso a recursos tecnológicos son predictores consistentes 
del desempeño escolar (Romero & Ventura, 2010).

El uso de modelos de machine learning para predecir el rendimiento estudiantil 
permite identificar patrones no lineales entre estas variables, orientando 
intervenciones tempranas y políticas educativas basadas en datos.

## 3. Análisis del Dataset

### 3.1 ¿De dónde viene?
El dataset fue obtenido de Kaggle. Contiene registros sintéticos de estudiantes 
diseñados para tareas de análisis de datos y machine learning en el ámbito educativo.

### 3.2 ¿Qué contiene?
El dataset cuenta con 10,000 registros y 14 columnas sin valores nulos, 
distribuidas en tres tipos:

| Tipo | Variables |
|---|---|
| Numéricas continuas | `study_hours_per_day`, `attendance_percentage`, `assignment_score`, `midterm_score`, `final_exam_score`, `participation_score`, `sleep_hours` |
| Categóricas ordinales | `parent_education` (High School < Bachelor < Master < PhD) |
| Binarias | `gender` (Male/Female), `internet_access` (Yes/No), `extra_classes` (No/Yes) |
| Descartadas | `student_id` (identificador), `overall_score` (data leakage), `grade` (target) |

### 3.3 ¿Qué información dan las muestras?
Cada registro representa un estudiante individual y describe sus hábitos de 
estudio, condiciones de aprendizaje, resultados en evaluaciones parciales y 
contexto socioeducativo. En conjunto, las muestras permiten caracterizar el 
perfil académico y personal asociado a cada nivel de desempeño final.

### 3.4 ¿Qué se quiere analizar?
Se busca predecir la calificación final del estudiante (`grade`: A, B, C, D, F) 
a partir de sus características académicas, conductuales y contextuales, 
utilizando modelos de clasificación supervisada. Se excluye `overall_score` 
por constituir data leakage — sus rangos por grado no se solapan, lo que 
indica que `grade` se deriva directamente de esta variable.

### 3.5 Transformaciones necesarias

| Variable | Transformación | Justificación |
|---|---|---|
| `gender`, `internet_access`, `extra_classes` | OneHotEncoder | Variables binarias sin orden natural |
| `parent_education` | OrdinalEncoder | Variable ordinal con jerarquía educativa definida |
| Variables numéricas | StandardScaler | Normaliza escala para modelos sensibles a magnitud |
| `student_id`, `overall_score` | Eliminadas | Identificador sin valor predictivo y data leakage |

### 3.6 ¿Qué resultado se podría encontrar?
Se espera que las variables con mayor poder predictivo sean `final_exam_score`, 
`midterm_score` y `assignment_score`. Las variables contextuales como 
`internet_access`, `extra_classes` y `parent_education` podrían mostrar 
diferencias entre grupos pero con menor capacidad predictiva individual.

Se anticipa que el MLP y SVM superen a la regresión logística en F1-score 
macro por su capacidad de capturar relaciones no lineales entre las variables.

In [22]:
import pandas as pd

df = pd.read_csv("student_performance_data (1).csv")

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   student_id             10000 non-null  int64  
 1   gender                 10000 non-null  object 
 2   study_hours_per_day    10000 non-null  float64
 3   attendance_percentage  10000 non-null  float64
 4   assignment_score       10000 non-null  float64
 5   midterm_score          10000 non-null  float64
 6   final_exam_score       10000 non-null  float64
 7   participation_score    10000 non-null  float64
 8   internet_access        10000 non-null  object 
 9   extra_classes          10000 non-null  object 
 10  parent_education       10000 non-null  object 
 11  sleep_hours            10000 non-null  float64
 12  overall_score          10000 non-null  float64
 13  grade                  10000 non-null  object 
dtypes: float64(8), int64(1), object(5)
memory usage: 1.1+ M

In [24]:
df["parent_education"].value_counts()





parent_education
High School    2528
Bachelor       2527
Master         2487
PhD            2458
Name: count, dtype: int64

EDA:

Objects:
* Gender (bool)
* internet_access (bool)
* extra_classes (bool)
* parent_education (cat ordinal)
* grade (cat ordinal)

Numericas:

* study_hours_per_day (hrs/day)
* attendance_percentage (%)
* assignment_score 
* midterm_score
* final_exam_score
* participation_score
* sleep_hours (hrs)
* overall_score






In [25]:
df.groupby("grade")["overall_score"].agg(["min", "max"])

,min,max
grade,,
A,85.0175,96.8795
B,70.0085,84.9915
C,55.0025,69.9980
D,40.0510,54.9985
F,33.2635,39.9570


In [26]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=["overall_score", "student_id","overall_score"])
y = df["grade"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)



In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler

bool_cols    = ["gender", "internet_access", "extra_classes"]
ordinal_cols = ["parent_education"]
num_cols     = ["study_hours_per_day", "attendance_percentage", "assignment_score",
                "midterm_score", "final_exam_score", "participation_score", "sleep_hours"]

preprocessor = ColumnTransformer(
    transformers=[
        ("bool",    OneHotEncoder(), bool_cols),
        ("ordinal", OrdinalEncoder(categories=[
                        ["High School", "Bachelor", "Master", "PhD"]
                    ]), ordinal_cols),
        ("num",     StandardScaler(), num_cols),
    ]
)


In [33]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier

pipeline_lr = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])

pipeline_svm = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", SVC(kernel="rbf", probability=True))
])

pipeline_mlp = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", MLPClassifier(max_iter=1000))
])

## Bayes lr

In [34]:
from skopt import BayesSearchCV
from skopt.space import Real, Categorical

param_lr = {
    "model__C": Real(1e-3, 100, prior="log-uniform"),
    "model__penalty": Categorical(["l1", "l2"]),
    "model__solver": Categorical(["liblinear", "saga"])
}

bayes_lr = BayesSearchCV(pipeline_lr, param_lr, n_iter=30, cv=5, scoring="f1_macro", n_jobs=-1, random_state=42)
bayes_lr.fit(X_train, y_train)

c:\Users\jorgo\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


,estimator,Pipeline(step..._iter=1000))])
,search_spaces,"{'model__C': Real(low=0.00...m='normalize'), 'model__penalty': Categorical(c...), prior=None), 'model__solver': Categorical(c...), prior=None)}"
,optimizer_kwargs,None
,n_iter,30
,scoring,'f1_macro'
,fit_params,None
,n_jobs,-1
,n_points,1
,iid,'deprecated'
,refit,True
,cv,5


## SVM

In [35]:
from skopt.space import Real

param_svm = {
    "model__C": Real(1e-3, 100, prior="log-uniform"),
    "model__gamma": Real(1e-4, 10, prior="log-uniform")
}

bayes_svm = BayesSearchCV(pipeline_svm, param_svm, n_iter=30, cv=5, scoring="f1_macro", n_jobs=-1, random_state=42)
bayes_svm.fit(X_train, y_train)

,estimator,Pipeline(step...ility=True))])
,search_spaces,"{'model__C': Real(low=0.00...m='normalize'), 'model__gamma': Real(low=0.00...m='normalize')}"
,optimizer_kwargs,None
,n_iter,30
,scoring,'f1_macro'
,fit_params,None
,n_jobs,-1
,n_points,1
,iid,'deprecated'
,refit,True
,cv,5


## MLP 

In [40]:
from sklearn.model_selection import GridSearchCV

param_mlp = {
    "model__hidden_layer_sizes": [(64,), (128,), (256,), (64, 64), (128, 64)],
    "model__learning_rate_init": [0.001, 0.01, 0.0001],
    "model__alpha": [0.0001, 0.001, 0.01]
}

search_mlp = GridSearchCV(pipeline_mlp, param_mlp, cv=5, scoring="f1_macro", n_jobs=-1)
search_mlp.fit(X_train, y_train)

,estimator,Pipeline(step..._iter=1000))])
,param_grid,"{'model__alpha': [0.0001, 0.001, ...], 'model__hidden_layer_sizes': [(64,), (128,), ...], 'model__learning_rate_init': [0.001, 0.01, ...]}"
,scoring,'f1_macro'
,n_jobs,-1
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,transformers,"[('bool', ...), ('ordinal', ...), ...]"


## Evaluación Final

In [42]:
from sklearn.metrics import f1_score, accuracy_score, roc_auc_score

# Predicciones
y_pred_lr  = bayes_lr.predict(X_test)
y_pred_svm = bayes_svm.predict(X_test)
y_pred_mlp = search_mlp.predict(X_test)

In [43]:
# Probabilidades para AUC
y_prob_lr  = bayes_lr.predict_proba(X_test)
y_prob_svm = bayes_svm.predict_proba(X_test)
y_prob_mlp = search_mlp.predict_proba(X_test)

In [44]:
# Métricas
resultados = pd.DataFrame({
    "Modelo": ["Logistic Regression", "SVM RBF", "MLP"],
    "F1 Macro": [
        f1_score(y_test, y_pred_lr,  average="macro"),
        f1_score(y_test, y_pred_svm, average="macro"),
        f1_score(y_test, y_pred_mlp, average="macro")
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_svm),
        accuracy_score(y_test, y_pred_mlp)
    ],
    "AUC Macro": [
        roc_auc_score(y_test, y_prob_lr,  multi_class="ovr", average="macro"),
        roc_auc_score(y_test, y_prob_svm, multi_class="ovr", average="macro"),
        roc_auc_score(y_test, y_prob_mlp, multi_class="ovr", average="macro")
    ]
}).round(4)

print(resultados)

                Modelo  F1 Macro  Accuracy  AUC Macro
0  Logistic Regression    0.9703    0.9945     1.0000
1              SVM RBF    0.9286    0.9830     0.9998
2                  MLP    0.9474    0.9845     0.9997


## 8. Comparación de Modelos

Los tres modelos obtuvieron un desempeño notablemente alto, con AUC Macro 
superior a 0.999 en todos los casos, lo que indica una capacidad discriminativa 
casi perfecta. La Regresión Logística obtuvo el mejor F1 Macro (0.9703) y 
Accuracy (0.9945), superando al SVM y al MLP en ambas métricas.

## 9. Conclusiones

Respecto al preprocesamiento, se identificó que `overall_score` constituye 
data leakage al derivarse directamente de `grade`, por lo que fue eliminada 
del conjunto de features. Las transformaciones aplicadas (OneHotEncoder, 
OrdinalEncoder y StandardScaler) permitieron preparar correctamente todas 
las variables para su uso en los tres modelos.

Respecto a la comparación de modelos, la Regresión Logística obtuvo el mejor 
desempeño con F1 Macro de 0.9703 y Accuracy de 0.9945, seguida del MLP 
(F1=0.9474) y SVM RBF (F1=0.9286). Contrario a lo esperado, el modelo lineal 
superó a los modelos no lineales, lo que sugiere que las relaciones entre las 
variables y el target son predominantemente lineales en este dataset.

Respecto al AUC-ROC, los tres modelos obtuvieron valores superiores a 0.999, 
indicando una capacidad discriminativa casi perfecta entre las cinco clases 
de rendimiento académico.

Respecto al balance rendimiento/costo computacional, la Regresión Logística 
resulta ser el modelo más conveniente para este problema, al combinar el mejor 
desempeño predictivo con el menor costo computacional de los tres modelos evaluados.

## 10. Referencias

Upcoder. (2024). *Student Performance Analytics Dataset* [Dataset]. Kaggle. 
https://www.kaggle.com/datasets/upcoderr/student-performance-analytics-dataset/data

Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., 
... & Duchesnay, É. (2011). Scikit-learn: Machine learning in Python. 
*Journal of Machine Learning Research, 12*, 2825–2830.

Head, T., Kumar, M., Nahrstaedt, H., Louppe, G., & Shcherbatyi, I. (2021). 
*scikit-optimize/scikit-optimize*. Zenodo. https://doi.org/10.5281/zenodo.4014775

Romero, C., & Ventura, S. (2010). Educational data mining: A review of the state 
of the art. *IEEE Transactions on Systems, Man, and Cybernetics, Part C, 40*(6), 
601–618.